project_id = "ioajkewinekfdoayvwqs"

[functions.generate-match-prediction]
verify_jwt = false

[functions.fetch-live-matches]
verify_jwt = false

[functions.fetch-matches-apisports]
verify_jwt = false

[functions.fetch-match-details-apisports]
verify_jwt = false

[functions.fetch-highlights]
verify_jwt = false

[functions.fetch-sports-feeds]
verify_jwt = false

[functions.initialize-season]
verify_jwt = false

[functions.generate-fixtures]
verify_jwt = false

[functions.simulate-match]
verify_jwt = false

[functions.simulate-match-user]
verify_jwt = false

[functions.process-season-end]
verify_jwt = false

[functions.create-notification]
verify_jwt = true

[functions.setup-dummy-data]
verify_jwt = true

[functions.fetch-league-standings]
verify_jwt = false

[functions.fetch-league-fixtures]
verify_jwt = false

[functions.fetch-league-top-scorers]
verify_jwt = false

[functions.check-goal-updates]
verify_jwt = false

[functions.send-goal-notification]
verify_jwt = false

[functions.update-live-scores]
verify_jwt = false

[functions.check-upcoming-matches]
verify_jwt = false

[functions.send-match-notification]
verify_jwt = false
